// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	quiz "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/quiz"
	gomock "go.uber.org/mock/gomock"
)

// MockSetLoader is a mock of SetLoader interface.
type MockSetLoader struct {
	ctrl     *gomock.Controller
	recorder *MockSetLoaderMockRecorder
	isgomock struct{}
}

// MockSetLoaderMockRecorder is the mock recorder for MockSetLoader.
type MockSetLoaderMockRecorder struct {
	mock *MockSetLoader
}

// NewMockSetLoader creates a new mock instance.
func NewMockSetLoader(ctrl *gomock.Controller) *MockSetLoader {
	mock := &MockSetLoader{ctrl: ctrl}
	mock.recorder = &MockSetLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetLoader) EXPECT() *MockSetLoaderMockRecorder {
	return m.recorder
}

// QuestionSet mocks base method.
func (m *MockSetLoader) QuestionSet(ctx context.Context, id quiz.QuestionSetID) (quiz.QuestionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionSet", ctx, id)
	ret0, _ := ret[0].(quiz.QuestionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuestionSet indicates an expected call of QuestionSet.
func (mr *MockSetLoaderMockRecorder) QuestionSet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionSet", reflect.TypeOf((*MockSetLoader)(nil).QuestionSet), ctx, id)
}
