// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	quiz "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/quiz"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRepository) CreateRoom(ctx context.Context, in quiz.CreateRoomInput) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, in)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRepositoryMockRecorder) CreateRoom(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRepository)(nil).CreateRoom), ctx, in)
}

// Live mocks base method.
func (m *MockRepository) Live(ctx context.Context, code quiz.Code) (quiz.LiveRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Live", ctx, code)
	ret0, _ := ret[0].(quiz.LiveRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Live indicates an expected call of Live.
func (mr *MockRepositoryMockRecorder) Live(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Live", reflect.TypeOf((*MockRepository)(nil).Live), ctx, code)
}

// Room mocks base method.
func (m *MockRepository) Room(ctx context.Context, code quiz.Code) (quiz.RoomRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Room", ctx, code)
	ret0, _ := ret[0].(quiz.RoomRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Room indicates an expected call of Room.
func (mr *MockRepositoryMockRecorder) Room(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Room", reflect.TypeOf((*MockRepository)(nil).Room), ctx, code)
}

// Start mocks base method.
func (m *MockRepository) Start(ctx context.Context, code quiz.Code, caller quiz.ParticipantID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, code, caller)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRepositoryMockRecorder) Start(ctx, code, caller any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRepository)(nil).Start), ctx, code, caller)
}
