// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mocks/store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	quiz "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/quiz"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateQuiz mocks base method.
func (m *MockStore) CreateQuiz(ctx context.Context, q quiz.NewQuiz, live func(context.Context) (int64, error)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuiz", ctx, q, live)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateQuiz indicates an expected call of CreateQuiz.
func (mr *MockStoreMockRecorder) CreateQuiz(ctx, q, live any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuiz", reflect.TypeOf((*MockStore)(nil).CreateQuiz), ctx, q, live)
}

// MarkRunning mocks base method.
func (m *MockStore) MarkRunning(ctx context.Context, code quiz.Code) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRunning", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRunning indicates an expected call of MarkRunning.
func (mr *MockStoreMockRecorder) MarkRunning(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRunning", reflect.TypeOf((*MockStore)(nil).MarkRunning), ctx, code)
}

// QuestionIDs mocks base method.
func (m *MockStore) QuestionIDs(ctx context.Context, id quiz.QuestionSetID) ([]quiz.QuestionID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionIDs", ctx, id)
	ret0, _ := ret[0].([]quiz.QuestionID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuestionIDs indicates an expected call of QuestionIDs.
func (mr *MockStoreMockRecorder) QuestionIDs(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionIDs", reflect.TypeOf((*MockStore)(nil).QuestionIDs), ctx, id)
}

// QuestionSets mocks base method.
func (m *MockStore) QuestionSets(ctx context.Context) ([]quiz.QuestionSetSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionSets", ctx)
	ret0, _ := ret[0].([]quiz.QuestionSetSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuestionSets indicates an expected call of QuestionSets.
func (mr *MockStoreMockRecorder) QuestionSets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionSets", reflect.TypeOf((*MockStore)(nil).QuestionSets), ctx)
}

// Quiz mocks base method.
func (m *MockStore) Quiz(ctx context.Context, code quiz.Code) (quiz.StoredQuiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quiz", ctx, code)
	ret0, _ := ret[0].(quiz.StoredQuiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Quiz indicates an expected call of Quiz.
func (mr *MockStoreMockRecorder) Quiz(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quiz", reflect.TypeOf((*MockStore)(nil).Quiz), ctx, code)
}
