// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	scoring "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/scoring"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// RecordAnswer mocks base method.
func (m *MockRepository) RecordAnswer(ctx context.Context, in scoring.AnswerInput) (scoring.AnswerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAnswer", ctx, in)
	ret0, _ := ret[0].(scoring.AnswerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordAnswer indicates an expected call of RecordAnswer.
func (mr *MockRepositoryMockRecorder) RecordAnswer(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAnswer", reflect.TypeOf((*MockRepository)(nil).RecordAnswer), ctx, in)
}
