/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dev/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a signed token (mocked identity provider)
         * @description Only available when `DEV_TOKENS_ENABLED=true`. Returns 404 otherwise.
         */
        post: operations["createDevToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/question-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List question sets a host can use */
        get: operations["listQuestionSets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a quiz room in the lobby (host only)
         * @description Generates a unique 6-character code (D16). The caller becomes the host.
         */
        post: operations["createQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["QuizCode"];
            };
            cookie?: never;
        };
        /**
         * Quiz status and settings
         * @description Served from Redis while live, from PostgreSQL once finished or expired.
         */
        get: operations["getQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{code}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["QuizCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the quiz (host only)
         * @description Accepted, not immediate: the first question is opened by a worker within
         *     one poll interval (≈100 ms) and announced over WebSocket (FR-3, FR-4).
         *     Repeating the call after a successful start returns 202 again (idempotent).
         */
        post: operations["startQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{code}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["QuizCode"];
            };
            cookie?: never;
        };
        /**
         * Full leaderboard, paginated (FR-27, FR-13)
         * @description Live standings from Redis while the quiz runs; final results from PostgreSQL once finished.
         */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (Redis and PostgreSQL reachable, not draining) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 6 characters without look-alikes (D16). Must match `schemas/common.json`.
         * @example K7Q2MX
         */
        QuizCode: string;
        /** @enum {string} */
        Role: "participant" | "host";
        DevTokenRequest: {
            role: components["schemas"]["Role"];
            /** @description Optional; generated when omitted. */
            participantId?: string;
        };
        /**
         * @example {
         *       "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1XzhmM2EyYyIsInJvbGUiOiJwYXJ0aWNpcGFudCJ9.sig",
         *       "participantId": "u_8f3a2c",
         *       "role": "participant",
         *       "expiresAt": "2026-09-28T10:15:00Z"
         *     }
         */
        DevToken: {
            token: string;
            participantId: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            expiresAt: string;
        };
        QuestionSetSummary: {
            id: string;
            title: string;
            questionCount: number;
        };
        CreateQuizRequest: {
            questionSetId: string;
            /** @default 15 */
            questionWindowSeconds: number;
            /** @default 5 */
            revealSeconds: number;
        };
        /** @enum {string} */
        QuizStatus: "lobby" | "question_open" | "question_closed" | "finished" | "expired";
        /**
         * @example {
         *       "code": "K7Q2MX",
         *       "questionSetId": "demo-quick",
         *       "status": "lobby",
         *       "questionCount": 3,
         *       "participantCount": 0,
         *       "questionWindowSeconds": 10,
         *       "revealSeconds": 3,
         *       "createdAt": "2026-09-28T10:00:00Z",
         *       "lobbyExpiresAt": "2026-09-28T10:30:00Z"
         *     }
         */
        Quiz: {
            code: components["schemas"]["QuizCode"];
            questionSetId: string;
            status: components["schemas"]["QuizStatus"];
            questionCount: number;
            participantCount: number;
            questionWindowSeconds: number;
            revealSeconds: number;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Present while in the lobby.
             */
            lobbyExpiresAt?: string;
            /**
             * Format: date-time
             * @description Present once the final results are saved.
             */
            finishedAt?: string;
        };
        /**
         * @example {
         *       "code": "K7Q2MX",
         *       "startRequested": true
         *     }
         */
        StartAccepted: {
            code: components["schemas"]["QuizCode"];
            /** @constant */
            startRequested: true;
        };
        LeaderboardEntry: {
            /** @description Equal scores share a rank (FR-24). */
            rank: number;
            participantId: string;
            displayName: string;
            score: number;
        };
        /**
         * @example {
         *       "code": "K7Q2MX",
         *       "status": "finished",
         *       "participantCount": 3,
         *       "offset": 0,
         *       "limit": 100,
         *       "entries": [
         *         {
         *           "rank": 1,
         *           "participantId": "u_8f3a2c",
         *           "displayName": "Rina",
         *           "score": 574
         *         },
         *         {
         *           "rank": 2,
         *           "participantId": "u_19bd07",
         *           "displayName": "Tomás",
         *           "score": 551
         *         },
         *         {
         *           "rank": 2,
         *           "participantId": "u_c4e611",
         *           "displayName": "Aiko",
         *           "score": 551
         *         }
         *       ]
         *     }
         */
        LeaderboardPage: {
            code: components["schemas"]["QuizCode"];
            status: components["schemas"]["QuizStatus"];
            participantCount: number;
            offset: number;
            limit: number;
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /** @enum {string} */
        ErrorCode: "invalid_request" | "unauthorized" | "forbidden" | "not_host" | "not_found" | "unknown_quiz" | "question_set_not_found" | "not_in_lobby" | "no_participants" | "unavailable" | "internal";
        /** @description RFC 9457 problem details, plus a machine-readable `code`. */
        Problem: {
            /**
             * Format: uri-reference
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            code: components["schemas"]["ErrorCode"];
            detail?: string;
        };
    };
    responses: {
        /** @description Invalid request body or parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Bad Request",
                 *       "status": 400,
                 *       "code": "invalid_request",
                 *       "detail": "questionWindowSeconds must be between 5 and 120"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid, or expired token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "code": "unauthorized"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Token lacks the required role, or caller is not this quiz's host */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "code": "not_host"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unknown quiz or question set (or dev tokens disabled) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "code": "unknown_quiz"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The quiz is not in a state that allows this (not in lobby, no participants yet) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "code": "no_participants"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error (a bug); logged with the request ID */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Internal Server Error",
                 *       "status": 500,
                 *       "code": "internal"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A dependency is unavailable; safe to retry after `Retry-After` */
        Unavailable: {
            headers: {
                /** @description Seconds */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Service Unavailable",
                 *       "status": 503,
                 *       "code": "unavailable"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        QuizCode: components["schemas"]["QuizCode"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createDevToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevTokenRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listQuestionSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available question sets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "demo-quick",
                     *           "title": "Quick demo",
                     *           "questionCount": 3
                     *         },
                     *         {
                     *           "id": "synonyms-everyday",
                     *           "title": "Everyday synonyms",
                     *           "questionCount": 10
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        items: components["schemas"]["QuestionSetSummary"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    createQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "questionSetId": "demo-quick",
                 *       "questionWindowSeconds": 10,
                 *       "revealSeconds": 3
                 *     }
                 */
                "application/json": components["schemas"]["CreateQuizRequest"];
            };
        };
        responses: {
            /** @description Quiz created */
            201: {
                headers: {
                    /** @example /api/v1/quizzes/K7Q2MX */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["QuizCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quiz */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quiz"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    startQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: components["parameters"]["QuizCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Start accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                code: components["parameters"]["QuizCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of the leaderboard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            503: components["responses"]["Unavailable"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
