// Code generated by MockGen. DO NOT EDIT.
// Source: pages.go
//
// Generated by this command:
//
//	mockgen -source=pages.go -destination=mocks/pages.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	leaderboard "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/leaderboard"
	quiz "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/quiz"
	gomock "go.uber.org/mock/gomock"
)

// MockLivePages is a mock of LivePages interface.
type MockLivePages struct {
	ctrl     *gomock.Controller
	recorder *MockLivePagesMockRecorder
	isgomock struct{}
}

// MockLivePagesMockRecorder is the mock recorder for MockLivePages.
type MockLivePagesMockRecorder struct {
	mock *MockLivePages
}

// NewMockLivePages creates a new mock instance.
func NewMockLivePages(ctrl *gomock.Controller) *MockLivePages {
	mock := &MockLivePages{ctrl: ctrl}
	mock.recorder = &MockLivePagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLivePages) EXPECT() *MockLivePagesMockRecorder {
	return m.recorder
}

// LivePage mocks base method.
func (m *MockLivePages) LivePage(ctx context.Context, code quiz.Code, offset, limit int) (leaderboard.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LivePage", ctx, code, offset, limit)
	ret0, _ := ret[0].(leaderboard.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LivePage indicates an expected call of LivePage.
func (mr *MockLivePagesMockRecorder) LivePage(ctx, code, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LivePage", reflect.TypeOf((*MockLivePages)(nil).LivePage), ctx, code, offset, limit)
}

// MockFinalPages is a mock of FinalPages interface.
type MockFinalPages struct {
	ctrl     *gomock.Controller
	recorder *MockFinalPagesMockRecorder
	isgomock struct{}
}

// MockFinalPagesMockRecorder is the mock recorder for MockFinalPages.
type MockFinalPagesMockRecorder struct {
	mock *MockFinalPages
}

// NewMockFinalPages creates a new mock instance.
func NewMockFinalPages(ctrl *gomock.Controller) *MockFinalPages {
	mock := &MockFinalPages{ctrl: ctrl}
	mock.recorder = &MockFinalPagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinalPages) EXPECT() *MockFinalPagesMockRecorder {
	return m.recorder
}

// FinalPage mocks base method.
func (m *MockFinalPages) FinalPage(ctx context.Context, code quiz.Code, offset, limit int) (leaderboard.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalPage", ctx, code, offset, limit)
	ret0, _ := ret[0].(leaderboard.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalPage indicates an expected call of FinalPage.
func (mr *MockFinalPagesMockRecorder) FinalPage(ctx, code, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalPage", reflect.TypeOf((*MockFinalPages)(nil).FinalPage), ctx, code, offset, limit)
}
