// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	history "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/history"
	quiz "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/quiz"
	gomock "go.uber.org/mock/gomock"
)

// MockLiveStore is a mock of LiveStore interface.
type MockLiveStore struct {
	ctrl     *gomock.Controller
	recorder *MockLiveStoreMockRecorder
	isgomock struct{}
}

// MockLiveStoreMockRecorder is the mock recorder for MockLiveStore.
type MockLiveStoreMockRecorder struct {
	mock *MockLiveStore
}

// NewMockLiveStore creates a new mock instance.
func NewMockLiveStore(ctrl *gomock.Controller) *MockLiveStore {
	mock := &MockLiveStore{ctrl: ctrl}
	mock.recorder = &MockLiveStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveStore) EXPECT() *MockLiveStoreMockRecorder {
	return m.recorder
}

// AckFlush mocks base method.
func (m *MockLiveStore) AckFlush(ctx context.Context, job history.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckFlush", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// AckFlush indicates an expected call of AckFlush.
func (mr *MockLiveStoreMockRecorder) AckFlush(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckFlush", reflect.TypeOf((*MockLiveStore)(nil).AckFlush), ctx, job)
}

// Claim mocks base method.
func (m *MockLiveStore) Claim(ctx context.Context, batch int, visibility time.Duration) ([]history.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", ctx, batch, visibility)
	ret0, _ := ret[0].([]history.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockLiveStoreMockRecorder) Claim(ctx, batch, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockLiveStore)(nil).Claim), ctx, batch, visibility)
}

// Defer mocks base method.
func (m *MockLiveStore) Defer(ctx context.Context, job history.Job, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Defer", ctx, job, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// Defer indicates an expected call of Defer.
func (mr *MockLiveStoreMockRecorder) Defer(ctx, job, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Defer", reflect.TypeOf((*MockLiveStore)(nil).Defer), ctx, job, delay)
}

// ExtendTTL mocks base method.
func (m *MockLiveStore) ExtendTTL(ctx context.Context, code quiz.Code, questionID quiz.QuestionID, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendTTL", ctx, code, questionID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtendTTL indicates an expected call of ExtendTTL.
func (mr *MockLiveStoreMockRecorder) ExtendTTL(ctx, code, questionID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendTTL", reflect.TypeOf((*MockLiveStore)(nil).ExtendTTL), ctx, code, questionID, ttl)
}

// PendingFlushes mocks base method.
func (m *MockLiveStore) PendingFlushes(ctx context.Context, code quiz.Code) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingFlushes", ctx, code)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingFlushes indicates an expected call of PendingFlushes.
func (mr *MockLiveStoreMockRecorder) PendingFlushes(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingFlushes", reflect.TypeOf((*MockLiveStore)(nil).PendingFlushes), ctx, code)
}

// ReadAnswers mocks base method.
func (m *MockLiveStore) ReadAnswers(ctx context.Context, code quiz.Code, questionID quiz.QuestionID) ([]history.StoredAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAnswers", ctx, code, questionID)
	ret0, _ := ret[0].([]history.StoredAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAnswers indicates an expected call of ReadAnswers.
func (mr *MockLiveStoreMockRecorder) ReadAnswers(ctx, code, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAnswers", reflect.TypeOf((*MockLiveStore)(nil).ReadAnswers), ctx, code, questionID)
}

// ReadFinal mocks base method.
func (m *MockLiveStore) ReadFinal(ctx context.Context, code quiz.Code) (history.FinalData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFinal", ctx, code)
	ret0, _ := ret[0].(history.FinalData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFinal indicates an expected call of ReadFinal.
func (mr *MockLiveStoreMockRecorder) ReadFinal(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFinal", reflect.TypeOf((*MockLiveStore)(nil).ReadFinal), ctx, code)
}

// Release mocks base method.
func (m *MockLiveStore) Release(ctx context.Context, job history.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockLiveStoreMockRecorder) Release(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockLiveStore)(nil).Release), ctx, job)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Finalize mocks base method.
func (m *MockStore) Finalize(ctx context.Context, in history.FinalizeInput) ([]history.Mismatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize", ctx, in)
	ret0, _ := ret[0].([]history.Mismatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Finalize indicates an expected call of Finalize.
func (mr *MockStoreMockRecorder) Finalize(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockStore)(nil).Finalize), ctx, in)
}

// SaveAnswers mocks base method.
func (m *MockStore) SaveAnswers(ctx context.Context, code quiz.Code, questionID quiz.QuestionID, answers []history.StoredAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAnswers", ctx, code, questionID, answers)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAnswers indicates an expected call of SaveAnswers.
func (mr *MockStoreMockRecorder) SaveAnswers(ctx, code, questionID, answers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAnswers", reflect.TypeOf((*MockStore)(nil).SaveAnswers), ctx, code, questionID, answers)
}
