// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	leaderboard "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/leaderboard"
	quiz "github.com/rizqyep/rizqyep-elsa-assignment/server/internal/quiz"
	gomock "go.uber.org/mock/gomock"
)

// MockQuizzes is a mock of Quizzes interface.
type MockQuizzes struct {
	ctrl     *gomock.Controller
	recorder *MockQuizzesMockRecorder
	isgomock struct{}
}

// MockQuizzesMockRecorder is the mock recorder for MockQuizzes.
type MockQuizzesMockRecorder struct {
	mock *MockQuizzes
}

// NewMockQuizzes creates a new mock instance.
func NewMockQuizzes(ctrl *gomock.Controller) *MockQuizzes {
	mock := &MockQuizzes{ctrl: ctrl}
	mock.recorder = &MockQuizzesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizzes) EXPECT() *MockQuizzesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuizzes) Create(ctx context.Context, in quiz.CreateInput) (quiz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(quiz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockQuizzesMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuizzes)(nil).Create), ctx, in)
}

// Get mocks base method.
func (m *MockQuizzes) Get(ctx context.Context, code quiz.Code) (quiz.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, code)
	ret0, _ := ret[0].(quiz.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQuizzesMockRecorder) Get(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuizzes)(nil).Get), ctx, code)
}

// QuestionSets mocks base method.
func (m *MockQuizzes) QuestionSets(ctx context.Context) ([]quiz.QuestionSetSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuestionSets", ctx)
	ret0, _ := ret[0].([]quiz.QuestionSetSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuestionSets indicates an expected call of QuestionSets.
func (mr *MockQuizzesMockRecorder) QuestionSets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuestionSets", reflect.TypeOf((*MockQuizzes)(nil).QuestionSets), ctx)
}

// Start mocks base method.
func (m *MockQuizzes) Start(ctx context.Context, code quiz.Code, caller quiz.ParticipantID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, code, caller)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockQuizzesMockRecorder) Start(ctx, code, caller any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockQuizzes)(nil).Start), ctx, code, caller)
}

// MockLeaderboards is a mock of Leaderboards interface.
type MockLeaderboards struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderboardsMockRecorder
	isgomock struct{}
}

// MockLeaderboardsMockRecorder is the mock recorder for MockLeaderboards.
type MockLeaderboardsMockRecorder struct {
	mock *MockLeaderboards
}

// NewMockLeaderboards creates a new mock instance.
func NewMockLeaderboards(ctrl *gomock.Controller) *MockLeaderboards {
	mock := &MockLeaderboards{ctrl: ctrl}
	mock.recorder = &MockLeaderboardsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderboards) EXPECT() *MockLeaderboardsMockRecorder {
	return m.recorder
}

// Page mocks base method.
func (m *MockLeaderboards) Page(ctx context.Context, code quiz.Code, offset, limit int) (leaderboard.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, code, offset, limit)
	ret0, _ := ret[0].(leaderboard.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Page indicates an expected call of Page.
func (mr *MockLeaderboardsMockRecorder) Page(ctx, code, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockLeaderboards)(nil).Page), ctx, code, offset, limit)
}
